2025/07/14 13:48:52 [notice] 1#1: ModSecurity-nginx v1.0.4 (rules loaded inline/local/remote: 0/10/0)
2025/07/14 13:48:52 [notice] 1#1: libmodsecurity3 version 3.0.14
2025/07/14 13:53:30 [error] 343#343: *447 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.18.0.1, server: fr.localhost, request: "GET /alive HTTP/1.1", upstream: "http://172.18.0.9:5173/alive", host: "entropy.local:2443"
2025/07/14 13:53:34 [error] 343#343: *493 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.18.0.1, server: fr.localhost, request: "GET /alive HTTP/1.1", upstream: "http://172.18.0.9:5173/alive", host: "entropy.local:2443"
2025/07/14 13:54:18 [error] 344#344: *840 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.18.0.1, server: fr.localhost, request: "GET /alive HTTP/1.1", upstream: "http://172.18.0.9:5173/alive", host: "entropy.local:2443"
2025/07/14 13:54:26 [error] 344#344: *970 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.18.0.1, server: fr.localhost, request: "GET /alive HTTP/1.1", upstream: "http://172.18.0.9:5173/alive", host: "entropy.local:2443"
2025/07/14 13:55:10 [error] 344#344: *1058 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.18.0.1, server: fr.localhost, request: "GET /alive HTTP/1.1", upstream: "http://172.18.0.9:5173/alive", host: "entropy.local:2443"
2025/07/14 13:55:18 [error] 344#344: *1104 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.18.0.1, server: fr.localhost, request: "GET /alive HTTP/1.1", upstream: "http://172.18.0.9:5173/alive", host: "entropy.local:2443"
2025/07/14 13:55:21 [error] 345#345: *1149 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.18.0.1, server: fr.localhost, request: "GET /alive HTTP/1.1", upstream: "http://172.18.0.9:5173/alive", host: "entropy.local:2443"
2025/07/14 13:55:41 [error] 345#345: *1152 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.18.0.1, server: fr.localhost, request: "GET /alive HTTP/1.1", upstream: "http://172.18.0.9:5173/alive", host: "entropy.local:2443"
2025/07/14 13:56:21 [error] 345#345: *1164 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.18.0.1, server: fr.localhost, request: "GET /alive HTTP/1.1", upstream: "http://172.18.0.9:5173/alive", host: "entropy.local:2443"
2025/07/14 13:56:25 [error] 345#345: *1208 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.18.0.1, server: fr.localhost, request: "GET /alive HTTP/1.1", upstream: "http://172.18.0.9:5173/alive", host: "entropy.local:2443"
2025/07/14 13:56:46 [error] 345#345: *1216 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.18.0.1, server: fr.localhost, request: "GET /alive HTTP/1.1", upstream: "http://172.18.0.9:5173/alive", host: "entropy.local:2443"
2025/07/14 13:56:53 [error] 345#345: *1260 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.18.0.1, server: fr.localhost, request: "GET /alive HTTP/1.1", upstream: "http://172.18.0.9:5173/alive", host: "entropy.local:2443"
2025/07/14 13:57:07 [error] 345#345: *1264 upstream prematurely closed connection while reading response header from upstream, client: 172.18.0.1, server: fr.localhost, request: "GET /alive HTTP/1.1", upstream: "http://172.18.0.9:5173/alive", host: "entropy.local:2443"
2025/07/14 13:57:07 [error] 347#347: *1449 upstream prematurely closed connection while reading response header from upstream, client: 172.18.0.1, server: fr.localhost, request: "GET /alive HTTP/1.1", upstream: "http://172.18.0.9:5173/alive", host: "entropy.local:2443"
2025/07/14 13:57:07 [error] 347#347: *1493 upstream prematurely closed connection while reading response header from upstream, client: 172.18.0.1, server: fr.localhost, request: "GET /alive HTTP/1.1", upstream: "http://172.18.0.9:5173/alive", host: "entropy.local:2443"
2025/07/14 13:57:07 [error] 345#345: *1308 upstream prematurely closed connection while reading response header from upstream, client: 172.18.0.1, server: fr.localhost, request: "GET /alive HTTP/1.1", upstream: "http://172.18.0.9:5173/alive", host: "entropy.local:2443"
2025/07/14 13:57:07 [error] 345#345: *1357 upstream prematurely closed connection while reading response header from upstream, client: 172.18.0.1, server: fr.localhost, request: "GET /alive HTTP/1.1", upstream: "http://172.18.0.9:5173/alive", host: "entropy.local:2443"
2025/07/14 13:57:07 [error] 345#345: *1402 upstream prematurely closed connection while reading response header from upstream, client: 172.18.0.1, server: fr.localhost, request: "GET /alive HTTP/1.1", upstream: "http://172.18.0.9:5173/alive", host: "entropy.local:2443"
2025/07/14 13:57:26 [notice] 1#1: ModSecurity-nginx v1.0.4 (rules loaded inline/local/remote: 0/10/0)
2025/07/14 13:57:26 [notice] 1#1: libmodsecurity3 version 3.0.14
2025/07/14 13:58:35 [error] 351#351: *50 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.18.0.1, server: fr.localhost, request: "GET /alive HTTP/1.1", upstream: "http://172.18.0.8:5173/alive", host: "entropy.local:2443"
2025/07/14 13:58:58 [error] 352#352: *55 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.18.0.1, server: fr.localhost, request: "GET /alive HTTP/1.1", upstream: "http://172.18.0.8:5173/alive", host: "entropy.local:2443"
2025/07/14 14:02:05 [error] 359#359: *105 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.18.0.1, server: fr.localhost, request: "GET /alive HTTP/1.1", upstream: "http://172.18.0.8:5173/alive", host: "entropy.local:2443"
2025/07/14 14:02:08 [error] 361#361: *152 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.18.0.1, server: fr.localhost, request: "GET /alive HTTP/1.1", upstream: "http://172.18.0.8:5173/alive", host: "entropy.local:2443"
2025/07/14 14:02:10 [error] 363#363: *198 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.18.0.1, server: fr.localhost, request: "GET /alive HTTP/1.1", upstream: "http://172.18.0.8:5173/alive", host: "entropy.local:2443"
2025/07/14 14:02:13 [error] 343#343: *244 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.18.0.1, server: fr.localhost, request: "GET /alive HTTP/1.1", upstream: "http://172.18.0.8:5173/alive", host: "entropy.local:2443"
2025/07/14 14:02:23 [error] 343#343: *290 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.18.0.1, server: fr.localhost, request: "GET /alive HTTP/1.1", upstream: "http://172.18.0.8:5173/alive", host: "entropy.local:2443"
2025/07/14 14:02:25 [error] 343#343: *337 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.18.0.1, server: fr.localhost, request: "GET /alive HTTP/1.1", upstream: "http://172.18.0.8:5173/alive", host: "entropy.local:2443"
2025/07/14 14:03:05 [error] 343#343: *383 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.18.0.1, server: fr.localhost, request: "GET /alive HTTP/1.1", upstream: "http://172.18.0.8:5173/alive", host: "entropy.local:2443"
2025/07/14 14:03:23 [error] 343#343: *432 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.18.0.1, server: fr.localhost, request: "GET /alive HTTP/1.1", upstream: "http://172.18.0.8:5173/alive", host: "entropy.local:2443"
2025/07/14 14:03:35 [error] 343#343: *480 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.18.0.1, server: fr.localhost, request: "GET /alive HTTP/1.1", upstream: "http://172.18.0.8:5173/alive", host: "entropy.local:2443"
2025/07/14 14:03:41 [error] 343#343: *528 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.18.0.1, server: fr.localhost, request: "GET /alive HTTP/1.1", upstream: "http://172.18.0.8:5173/alive", host: "entropy.local:2443"
2025/07/14 14:03:50 [error] 343#343: *576 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.18.0.1, server: fr.localhost, request: "GET /alive HTTP/1.1", upstream: "http://172.18.0.8:5173/alive", host: "entropy.local:2443"
2025/07/14 14:03:53 [error] 344#344: *623 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.18.0.1, server: fr.localhost, request: "GET /alive HTTP/1.1", upstream: "http://172.18.0.8:5173/alive", host: "entropy.local:2443"
2025/07/14 14:05:08 [error] 344#344: *680 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.18.0.1, server: fr.localhost, request: "GET /alive HTTP/1.1", upstream: "http://172.18.0.8:5173/alive", host: "entropy.local:2443"
2025/07/14 14:12:29 [error] 346#346: *1040 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.18.0.1, server: fr.localhost, request: "GET /alive HTTP/1.1", upstream: "http://172.18.0.8:5173/alive", host: "entropy.local:2443"
2025/07/14 14:12:46 [error] 346#346: *1089 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.18.0.1, server: fr.localhost, request: "GET /alive HTTP/1.1", upstream: "http://172.18.0.8:5173/alive", host: "entropy.local:2443"
2025/07/14 14:12:49 [error] 346#346: *1136 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.18.0.1, server: fr.localhost, request: "GET /alive HTTP/1.1", upstream: "http://172.18.0.8:5173/alive", host: "entropy.local:2443"
2025/07/14 14:13:01 [error] 346#346: *1184 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.18.0.1, server: fr.localhost, request: "GET /alive HTTP/1.1", upstream: "http://172.18.0.8:5173/alive", host: "entropy.local:2443"
2025/07/14 14:13:22 [error] 346#346: *1187 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.18.0.1, server: fr.localhost, request: "GET /alive HTTP/1.1", upstream: "http://172.18.0.8:5173/alive", host: "entropy.local:2443"
2025/07/14 18:07:00 [notice] 1#1: ModSecurity-nginx v1.0.4 (rules loaded inline/local/remote: 0/10/0)
2025/07/14 18:07:00 [notice] 1#1: libmodsecurity3 version 3.0.14
2025/07/14 18:11:59 [notice] 1#1: ModSecurity-nginx v1.0.4 (rules loaded inline/local/remote: 0/10/0)
2025/07/14 18:11:59 [notice] 1#1: libmodsecurity3 version 3.0.14
2025/07/14 18:14:09 [notice] 1#1: ModSecurity-nginx v1.0.4 (rules loaded inline/local/remote: 0/10/0)
2025/07/14 18:14:09 [notice] 1#1: libmodsecurity3 version 3.0.14
2025/07/14 18:17:24 [notice] 1#1: ModSecurity-nginx v1.0.4 (rules loaded inline/local/remote: 0/10/0)
2025/07/14 18:17:24 [notice] 1#1: libmodsecurity3 version 3.0.14
2025/07/14 18:23:25 [notice] 1#1: ModSecurity-nginx v1.0.4 (rules loaded inline/local/remote: 0/10/0)
2025/07/14 18:23:25 [notice] 1#1: libmodsecurity3 version 3.0.14
2025/07/14 18:25:55 [notice] 1#1: ModSecurity-nginx v1.0.4 (rules loaded inline/local/remote: 0/10/0)
2025/07/14 18:25:55 [notice] 1#1: libmodsecurity3 version 3.0.14
2025/07/14 18:34:54 [error] 353#353: *12 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: fr.localhost, request: "POST /api/auth/register HTTP/1.1", upstream: "http://172.18.0.7:8000/auth/register", host: "entropy.local:2443", referrer: "https://entropy.local:2443/create-account"
2025/07/14 18:34:54 [error] 344#344: *43 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: fr.localhost, request: "POST /api/auth/register HTTP/1.1", upstream: "http://172.18.0.7:8000/auth/register", host: "entropy.local:2443", referrer: "https://entropy.local:2443/create-account"
2025/07/14 18:37:17 [notice] 1#1: ModSecurity-nginx v1.0.4 (rules loaded inline/local/remote: 0/10/0)
2025/07/14 18:37:17 [notice] 1#1: libmodsecurity3 version 3.0.14
2025/07/14 18:38:24 [error] 132#132: *13 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: fr.localhost, request: "POST /api/auth/register HTTP/1.1", upstream: "http://172.18.0.7:8000/auth/register", host: "entropy.local:2443", referrer: "https://entropy.local:2443/create-account"
2025/07/14 18:38:24 [error] 128#128: *5 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: fr.localhost, request: "POST /api/auth/register HTTP/1.1", upstream: "http://172.18.0.7:8000/auth/register", host: "entropy.local:2443", referrer: "https://entropy.local:2443/create-account"
2025/07/14 18:59:18 [warn] 127#127: *302 an upstream response is buffered to a temporary file /var/cache/nginx/proxy_temp/1/00/0000000001 while reading upstream, client: 172.18.0.1, server: fr.localhost, request: "GET /@vite/client HTTP/1.1", upstream: "http://172.18.0.8:5173/@vite/client", host: "entropy.local:2443", referrer: "https://entropy.local:2443/login"
2025/07/14 21:11:17 [warn] 130#130: *2188 an upstream response is buffered to a temporary file /var/cache/nginx/proxy_temp/2/00/0000000002 while reading upstream, client: 172.18.0.1, server: fr.localhost, request: "GET /@vite/client HTTP/1.1", upstream: "http://172.18.0.8:5173/@vite/client", host: "entropy.local:2443", referrer: "https://entropy.local:2443/login"
2025/07/16 13:11:13 [notice] 1#1: ModSecurity-nginx v1.0.4 (rules loaded inline/local/remote: 0/10/0)
2025/07/16 13:11:13 [notice] 1#1: libmodsecurity3 version 3.0.14
2025/07/16 13:11:24 [warn] 345#345: *3 an upstream response is buffered to a temporary file /var/cache/nginx/proxy_temp/1/00/0000000001 while reading upstream, client: 172.18.0.1, server: fr.localhost, request: "GET /@vite/client HTTP/1.1", upstream: "http://172.18.0.9:5173/@vite/client", host: "entropy.local:2443", referrer: "https://entropy.local:2443/"
2025/07/16 13:14:57 [notice] 1#1: ModSecurity-nginx v1.0.4 (rules loaded inline/local/remote: 0/10/0)
2025/07/16 13:14:57 [notice] 1#1: libmodsecurity3 version 3.0.14
2025/07/16 13:15:59 [error] 344#344: *96 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: fr.localhost, request: "POST /api/auth/login HTTP/1.1", upstream: "http://172.18.0.7:8000/auth/login", host: "entropy.local:2443", referrer: "https://entropy.local:2443/login"
2025/07/16 13:18:59 [notice] 1#1: ModSecurity-nginx v1.0.4 (rules loaded inline/local/remote: 0/10/0)
2025/07/16 13:18:59 [notice] 1#1: libmodsecurity3 version 3.0.14
2025/07/16 13:19:03 [warn] 345#345: *3 an upstream response is buffered to a temporary file /var/cache/nginx/proxy_temp/1/00/0000000001 while reading upstream, client: 172.18.0.1, server: fr.localhost, request: "GET /@vite/client HTTP/1.1", upstream: "http://172.18.0.8:5173/@vite/client", host: "entropy.local:2443", referrer: "https://entropy.local:2443/login"
2025/07/16 13:30:49 [warn] 346#346: *216 an upstream response is buffered to a temporary file /var/cache/nginx/proxy_temp/2/00/0000000002 while reading upstream, client: 172.18.0.1, server: fr.localhost, request: "GET /@vite/client HTTP/1.1", upstream: "http://172.18.0.8:5173/@vite/client", host: "entropy.local:2443", referrer: "https://entropy.local:2443/main"
2025/07/16 13:47:53 [notice] 1#1: ModSecurity-nginx v1.0.4 (rules loaded inline/local/remote: 0/10/0)
2025/07/16 13:47:53 [notice] 1#1: libmodsecurity3 version 3.0.14
2025/07/16 14:20:47 [notice] 1#1: ModSecurity-nginx v1.0.4 (rules loaded inline/local/remote: 0/10/0)
2025/07/16 14:20:47 [notice] 1#1: libmodsecurity3 version 3.0.14
2025/07/16 14:49:44 [notice] 1#1: ModSecurity-nginx v1.0.4 (rules loaded inline/local/remote: 0/10/0)
2025/07/16 14:49:44 [notice] 1#1: libmodsecurity3 version 3.0.14
2025/07/16 14:53:57 [warn] 344#344: *93 an upstream response is buffered to a temporary file /var/cache/nginx/proxy_temp/1/00/0000000001 while reading upstream, client: 172.18.0.1, server: fr.localhost, request: "GET /@vite/client HTTP/1.1", upstream: "http://172.18.0.8:5173/@vite/client", host: "entropy.local:2443", referrer: "https://entropy.local:2443/login"
2025/07/16 14:56:10 [notice] 1#1: ModSecurity-nginx v1.0.4 (rules loaded inline/local/remote: 0/10/0)
2025/07/16 14:56:10 [notice] 1#1: libmodsecurity3 version 3.0.14
2025/07/16 15:12:35 [warn] 348#348: *294 an upstream response is buffered to a temporary file /var/cache/nginx/proxy_temp/1/00/0000000001 while reading upstream, client: 172.18.0.1, server: fr.localhost, request: "GET /@vite/client HTTP/1.1", upstream: "http://172.18.0.8:5173/@vite/client", host: "entropy.local:2443", referrer: "https://entropy.local:2443/login"
2025/07/16 17:58:15 [notice] 1#1: ModSecurity-nginx v1.0.4 (rules loaded inline/local/remote: 0/10/0)
2025/07/16 17:58:15 [notice] 1#1: libmodsecurity3 version 3.0.14
2025/07/16 18:06:46 [error] 345#345: *239 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: fr.localhost, request: "GET /api/auth/verify HTTP/1.1", upstream: "http://172.18.0.7:8000/auth/verify", host: "entropy.local:2443", referrer: "https://entropy.local:2443/main"
2025/07/16 18:06:46 [error] 345#345: *239 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: fr.localhost, request: "GET /api/auth/verify HTTP/1.1", upstream: "http://172.18.0.7:8000/auth/verify", host: "entropy.local:2443", referrer: "https://entropy.local:2443/main"
2025/07/16 23:05:42 [emerg] 1#1: host not found in upstream "frontend" in /etc/nginx/nginx.conf:76
2025/07/16 23:06:01 [notice] 1#1: ModSecurity-nginx v1.0.4 (rules loaded inline/local/remote: 0/10/0)
2025/07/16 23:06:01 [notice] 1#1: libmodsecurity3 version 3.0.14
2025/07/16 23:09:25 [notice] 1#1: ModSecurity-nginx v1.0.4 (rules loaded inline/local/remote: 0/10/0)
2025/07/16 23:09:25 [notice] 1#1: libmodsecurity3 version 3.0.14
2025/07/16 23:11:03 [notice] 1#1: ModSecurity-nginx v1.0.4 (rules loaded inline/local/remote: 0/10/0)
2025/07/16 23:11:03 [notice] 1#1: libmodsecurity3 version 3.0.14
2025/07/16 23:39:35 [notice] 1#1: ModSecurity-nginx v1.0.4 (rules loaded inline/local/remote: 0/10/0)
2025/07/16 23:39:35 [notice] 1#1: libmodsecurity3 version 3.0.14
2025/07/16 23:52:55 [notice] 1#1: ModSecurity-nginx v1.0.4 (rules loaded inline/local/remote: 0/10/0)
2025/07/16 23:52:55 [notice] 1#1: libmodsecurity3 version 3.0.14
2025/07/17 00:00:04 [notice] 1#1: ModSecurity-nginx v1.0.4 (rules loaded inline/local/remote: 0/10/0)
2025/07/17 00:00:04 [notice] 1#1: libmodsecurity3 version 3.0.14
2025/07/17 00:05:40 [notice] 1#1: ModSecurity-nginx v1.0.4 (rules loaded inline/local/remote: 0/10/0)
2025/07/17 00:05:40 [notice] 1#1: libmodsecurity3 version 3.0.14
2025/07/17 00:07:23 [warn] 347#347: *5 an upstream response is buffered to a temporary file /var/cache/nginx/proxy_temp/1/00/0000000001 while reading upstream, client: 172.19.0.1, server: fr.localhost, request: "GET /@vite/client HTTP/1.1", upstream: "http://172.19.0.8:5173/@vite/client", host: "entropy.local:2443", referrer: "https://entropy.local:2443/block1v1"
2025/07/17 12:53:05 [notice] 1#1: ModSecurity-nginx v1.0.4 (rules loaded inline/local/remote: 0/10/0)
2025/07/17 12:53:05 [notice] 1#1: libmodsecurity3 version 3.0.14
2025/07/17 15:07:13 [notice] 1#1: ModSecurity-nginx v1.0.4 (rules loaded inline/local/remote: 0/10/0)
2025/07/17 15:07:13 [notice] 1#1: libmodsecurity3 version 3.0.14
2025/07/17 15:07:49 [warn] 346#346: *4 an upstream response is buffered to a temporary file /var/cache/nginx/proxy_temp/1/00/0000000001 while reading upstream, client: 172.18.0.1, server: fr.localhost, request: "GET /@vite/client HTTP/1.1", upstream: "http://172.18.0.9:5173/@vite/client", host: "localhost:2443", referrer: "https://localhost:2443/"
2025/07/17 17:26:59 [error] 354#354: *2680 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: fr.localhost, request: "GET /api/auth/verify HTTP/1.1", upstream: "http://172.18.0.7:8000/auth/verify", host: "localhost:2443", referrer: "https://localhost:2443/2fa"
2025/07/17 17:26:59 [error] 354#354: *2680 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: fr.localhost, request: "GET /api/auth/verify HTTP/1.1", upstream: "http://172.18.0.7:8000/auth/verify", host: "localhost:2443", referrer: "https://localhost:2443/2fa"
2025/07/17 17:27:04 [error] 355#355: *2699 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: fr.localhost, request: "GET /api/auth/verify HTTP/1.1", upstream: "http://172.18.0.7:8000/auth/verify", host: "localhost:2443", referrer: "https://localhost:2443/2fa"
2025/07/17 17:27:04 [error] 355#355: *2699 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: fr.localhost, request: "GET /api/auth/verify HTTP/1.1", upstream: "http://172.18.0.7:8000/auth/verify", host: "localhost:2443", referrer: "https://localhost:2443/2fa"
2025/07/17 17:27:04 [error] 355#355: *2699 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: fr.localhost, request: "GET /api/user/?userid=undefined HTTP/1.1", upstream: "http://172.18.0.7:8000/user/?userid=undefined", host: "localhost:2443", referrer: "https://localhost:2443/2fa"
2025/07/17 17:27:05 [error] 354#354: *2680 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: fr.localhost, request: "GET /api/auth/verify HTTP/1.1", upstream: "http://172.18.0.7:8000/auth/verify", host: "localhost:2443", referrer: "https://localhost:2443/2fa"
2025/07/17 17:27:05 [error] 354#354: *2680 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: fr.localhost, request: "GET /api/auth/verify HTTP/1.1", upstream: "http://172.18.0.7:8000/auth/verify", host: "localhost:2443", referrer: "https://localhost:2443/2fa"
2025/07/17 17:27:05 [error] 354#354: *2680 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: fr.localhost, request: "GET /api/user/?userid=undefined HTTP/1.1", upstream: "http://172.18.0.7:8000/user/?userid=undefined", host: "localhost:2443", referrer: "https://localhost:2443/2fa"
2025/07/17 17:27:30 [error] 354#354: *2680 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: fr.localhost, request: "GET /api/auth/verify HTTP/1.1", upstream: "http://172.18.0.7:8000/auth/verify", host: "localhost:2443", referrer: "https://localhost:2443/2fa"
2025/07/17 17:27:30 [error] 354#354: *2680 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: fr.localhost, request: "GET /api/auth/verify HTTP/1.1", upstream: "http://172.18.0.7:8000/auth/verify", host: "localhost:2443", referrer: "https://localhost:2443/2fa"
2025/07/17 17:27:30 [error] 354#354: *2680 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: fr.localhost, request: "GET /api/me HTTP/1.1", upstream: "http://172.18.0.7:8000/me", host: "localhost:2443", referrer: "https://localhost:2443/2fa"
2025/07/17 17:27:41 [error] 354#354: *2680 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: fr.localhost, request: "GET /api/auth/verify HTTP/1.1", upstream: "http://172.18.0.7:8000/auth/verify", host: "localhost:2443", referrer: "https://localhost:2443/2fa"
2025/07/17 17:27:41 [error] 354#354: *2680 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: fr.localhost, request: "GET /api/auth/verify HTTP/1.1", upstream: "http://172.18.0.7:8000/auth/verify", host: "localhost:2443", referrer: "https://localhost:2443/2fa"
2025/07/17 17:27:41 [error] 355#355: *2699 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: fr.localhost, request: "GET /api/me HTTP/1.1", upstream: "http://172.18.0.7:8000/me", host: "localhost:2443", referrer: "https://localhost:2443/2fa"
2025/07/17 17:27:43 [error] 354#354: *2680 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: fr.localhost, request: "GET /api/auth/verify HTTP/1.1", upstream: "http://172.18.0.7:8000/auth/verify", host: "localhost:2443", referrer: "https://localhost:2443/2fa"
2025/07/17 17:27:43 [error] 354#354: *2680 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: fr.localhost, request: "GET /api/auth/verify HTTP/1.1", upstream: "http://172.18.0.7:8000/auth/verify", host: "localhost:2443", referrer: "https://localhost:2443/2fa"
2025/07/17 17:27:45 [error] 355#355: *2699 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: fr.localhost, request: "GET /api/auth/verify HTTP/1.1", upstream: "http://172.18.0.7:8000/auth/verify", host: "localhost:2443", referrer: "https://localhost:2443/2fa"
2025/07/17 17:27:45 [error] 355#355: *2699 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: fr.localhost, request: "GET /api/auth/verify HTTP/1.1", upstream: "http://172.18.0.7:8000/auth/verify", host: "localhost:2443", referrer: "https://localhost:2443/2fa"
2025/07/17 17:27:45 [error] 354#354: *2698 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: fr.localhost, request: "GET /api/me HTTP/1.1", upstream: "http://172.18.0.7:8000/me", host: "localhost:2443", referrer: "https://localhost:2443/2fa"
2025/07/17 17:27:47 [error] 355#355: *2699 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: fr.localhost, request: "GET /api/auth/verify HTTP/1.1", upstream: "http://172.18.0.7:8000/auth/verify", host: "localhost:2443", referrer: "https://localhost:2443/2fa"
2025/07/17 17:27:47 [error] 355#355: *2699 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: fr.localhost, request: "GET /api/auth/verify HTTP/1.1", upstream: "http://172.18.0.7:8000/auth/verify", host: "localhost:2443", referrer: "https://localhost:2443/2fa"
2025/07/17 17:27:47 [error] 355#355: *2699 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: fr.localhost, request: "GET /api/me HTTP/1.1", upstream: "http://172.18.0.7:8000/me", host: "localhost:2443", referrer: "https://localhost:2443/2fa"
2025/07/17 17:32:46 [error] 354#354: *3115 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: fr.localhost, request: "GET /api/auth/verify HTTP/1.1", upstream: "http://172.18.0.7:8000/auth/verify", host: "localhost:2443", referrer: "https://localhost:2443/2fa"
2025/07/17 17:32:46 [error] 354#354: *3115 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: fr.localhost, request: "GET /api/auth/verify HTTP/1.1", upstream: "http://172.18.0.7:8000/auth/verify", host: "localhost:2443", referrer: "https://localhost:2443/2fa"
2025/07/17 17:32:46 [error] 354#354: *3115 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: fr.localhost, request: "GET /api/me HTTP/1.1", upstream: "http://172.18.0.7:8000/me", host: "localhost:2443", referrer: "https://localhost:2443/2fa"
2025/07/17 17:33:56 [error] 354#354: *3116 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: fr.localhost, request: "GET /api/auth/verify HTTP/1.1", upstream: "http://172.18.0.7:8000/auth/verify", host: "localhost:2443", referrer: "https://localhost:2443/2fa"
2025/07/17 17:33:56 [error] 354#354: *3116 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: fr.localhost, request: "GET /api/auth/verify HTTP/1.1", upstream: "http://172.18.0.7:8000/auth/verify", host: "localhost:2443", referrer: "https://localhost:2443/2fa"
2025/07/17 17:33:56 [error] 354#354: *3116 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: fr.localhost, request: "GET /api/me HTTP/1.1", upstream: "http://172.18.0.7:8000/me", host: "localhost:2443", referrer: "https://localhost:2443/2fa"
2025/07/17 17:35:46 [error] 356#356: *3786 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: fr.localhost, request: "GET /api/auth/verify HTTP/1.1", upstream: "http://172.18.0.7:8000/auth/verify", host: "localhost:2443", referrer: "https://localhost:2443/2fa"
2025/07/17 17:35:46 [error] 356#356: *3786 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: fr.localhost, request: "GET /api/auth/verify HTTP/1.1", upstream: "http://172.18.0.7:8000/auth/verify", host: "localhost:2443", referrer: "https://localhost:2443/2fa"
2025/07/17 17:35:46 [error] 356#356: *3786 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: fr.localhost, request: "GET /api/me/undefined HTTP/1.1", upstream: "http://172.18.0.7:8000/me/undefined", host: "localhost:2443", referrer: "https://localhost:2443/2fa"
2025/07/17 17:35:46 [error] 356#356: *3787 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: fr.localhost, request: "GET /api/me HTTP/1.1", upstream: "http://172.18.0.7:8000/me", host: "localhost:2443", referrer: "https://localhost:2443/2fa"
2025/07/17 17:49:49 [error] 360#360: *5087 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: fr.localhost, request: "GET /api/auth/verify HTTP/1.1", upstream: "http://172.18.0.7:8000/auth/verify", host: "localhost:2443", referrer: "https://localhost:2443/2fa"
2025/07/17 17:49:49 [error] 360#360: *5087 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: fr.localhost, request: "GET /api/auth/verify HTTP/1.1", upstream: "http://172.18.0.7:8000/auth/verify", host: "localhost:2443", referrer: "https://localhost:2443/2fa"
2025/07/17 17:49:49 [error] 360#360: *5087 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: fr.localhost, request: "GET /api/me HTTP/1.1", upstream: "http://172.18.0.7:8000/me", host: "localhost:2443", referrer: "https://localhost:2443/2fa"
2025/07/17 17:50:41 [error] 360#360: *5087 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: fr.localhost, request: "GET /api/auth/verify HTTP/1.1", upstream: "http://172.18.0.7:8000/auth/verify", host: "localhost:2443", referrer: "https://localhost:2443/2fa"
2025/07/17 17:50:41 [error] 360#360: *5087 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: fr.localhost, request: "GET /api/auth/verify HTTP/1.1", upstream: "http://172.18.0.7:8000/auth/verify", host: "localhost:2443", referrer: "https://localhost:2443/2fa"
2025/07/17 17:50:41 [error] 360#360: *5084 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: fr.localhost, request: "GET /api/me HTTP/1.1", upstream: "http://172.18.0.7:8000/me", host: "localhost:2443", referrer: "https://localhost:2443/2fa"
2025/07/17 17:50:53 [error] 360#360: *5087 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: fr.localhost, request: "GET /api/auth/verify HTTP/1.1", upstream: "http://172.18.0.7:8000/auth/verify", host: "localhost:2443", referrer: "https://localhost:2443/2fa"
2025/07/17 17:50:53 [error] 360#360: *5087 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: fr.localhost, request: "GET /api/auth/verify HTTP/1.1", upstream: "http://172.18.0.7:8000/auth/verify", host: "localhost:2443", referrer: "https://localhost:2443/2fa"
2025/07/17 17:50:53 [error] 360#360: *5087 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: fr.localhost, request: "GET /api/me HTTP/1.1", upstream: "http://172.18.0.7:8000/me", host: "localhost:2443", referrer: "https://localhost:2443/2fa"
2025/07/17 17:52:16 [error] 360#360: *5313 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: fr.localhost, request: "GET /api/auth/verify HTTP/1.1", upstream: "http://172.18.0.7:8000/auth/verify", host: "localhost:2443", referrer: "https://localhost:2443/2fa"
2025/07/17 17:52:16 [error] 360#360: *5313 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: fr.localhost, request: "GET /api/auth/verify HTTP/1.1", upstream: "http://172.18.0.7:8000/auth/verify", host: "localhost:2443", referrer: "https://localhost:2443/2fa"
2025/07/17 17:52:17 [error] 360#360: *5313 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: fr.localhost, request: "GET /api/me HTTP/1.1", upstream: "http://172.18.0.7:8000/me", host: "localhost:2443", referrer: "https://localhost:2443/2fa"
2025/07/17 17:52:20 [error] 360#360: *5313 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: fr.localhost, request: "GET /api/auth/verify HTTP/1.1", upstream: "http://172.18.0.7:8000/auth/verify", host: "localhost:2443", referrer: "https://localhost:2443/2fa"
2025/07/17 17:52:20 [error] 360#360: *5317 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: fr.localhost, request: "GET /api/auth/verify HTTP/1.1", upstream: "http://172.18.0.7:8000/auth/verify", host: "localhost:2443", referrer: "https://localhost:2443/2fa"
2025/07/17 17:52:21 [error] 360#360: *5313 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: fr.localhost, request: "GET /api/me HTTP/1.1", upstream: "http://172.18.0.7:8000/me", host: "localhost:2443", referrer: "https://localhost:2443/2fa"
2025/07/17 17:52:26 [error] 360#360: *5313 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: fr.localhost, request: "GET /api/auth/verify HTTP/1.1", upstream: "http://172.18.0.7:8000/auth/verify", host: "localhost:2443", referrer: "https://localhost:2443/2fa"
2025/07/17 17:52:26 [error] 360#360: *5317 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: fr.localhost, request: "GET /api/auth/verify HTTP/1.1", upstream: "http://172.18.0.7:8000/auth/verify", host: "localhost:2443", referrer: "https://localhost:2443/2fa"
2025/07/17 17:52:26 [error] 360#360: *5313 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: fr.localhost, request: "GET /api/me HTTP/1.1", upstream: "http://172.18.0.7:8000/me", host: "localhost:2443", referrer: "https://localhost:2443/2fa"
2025/07/17 17:54:13 [notice] 1#1: ModSecurity-nginx v1.0.4 (rules loaded inline/local/remote: 0/10/0)
2025/07/17 17:54:13 [notice] 1#1: libmodsecurity3 version 3.0.14
2025/07/17 17:54:16 [error] 344#344: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: fr.localhost, request: "GET /api/auth/verify HTTP/1.1", upstream: "http://172.18.0.7:8000/auth/verify", host: "localhost:2443", referrer: "https://localhost:2443/"
2025/07/17 17:54:18 [error] 344#344: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: fr.localhost, request: "GET /api/auth/verify HTTP/1.1", upstream: "http://172.18.0.7:8000/auth/verify", host: "localhost:2443", referrer: "https://localhost:2443/profil"
2025/07/17 17:54:18 [error] 344#344: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: fr.localhost, request: "GET /api/me HTTP/1.1", upstream: "http://172.18.0.7:8000/me", host: "localhost:2443", referrer: "https://localhost:2443/profil"
2025/07/17 17:54:18 [error] 344#344: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: fr.localhost, request: "GET /api/auth/verify HTTP/1.1", upstream: "http://172.18.0.7:8000/auth/verify", host: "localhost:2443", referrer: "https://localhost:2443/profil"
2025/07/17 17:54:18 [error] 346#346: *6 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: fr.localhost, request: "GET /api/uploads/avatar.png HTTP/1.1", upstream: "http://172.18.0.7:8000/uploads/avatar.png", host: "localhost:2443", referrer: "https://localhost:2443/profil"
2025/07/17 17:54:28 [error] 344#344: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: fr.localhost, request: "POST /api/auth/login HTTP/1.1", upstream: "http://172.18.0.7:8000/auth/login", host: "localhost:2443", referrer: "https://localhost:2443/login"
2025/07/17 17:58:35 [notice] 1#1: ModSecurity-nginx v1.0.4 (rules loaded inline/local/remote: 0/10/0)
2025/07/17 17:58:35 [notice] 1#1: libmodsecurity3 version 3.0.14
2025/07/17 18:00:04 [notice] 1#1: ModSecurity-nginx v1.0.4 (rules loaded inline/local/remote: 0/10/0)
2025/07/17 18:00:04 [notice] 1#1: libmodsecurity3 version 3.0.14
2025/07/17 18:06:14 [notice] 1#1: ModSecurity-nginx v1.0.4 (rules loaded inline/local/remote: 0/10/0)
2025/07/17 18:06:14 [notice] 1#1: libmodsecurity3 version 3.0.14
